---
title: "Assignment 4"
author: "Coral Negron"
date: "December 1, 2018"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##Problem 1
```{r, message=False}
data(College, package = "ISLR")
str(College, max.level = 1)
```
```{r, message=False}
help(College, package = 'ISLR')
```
a.
```{r, message=False}
library(caret)
data(College, package = "ISLR")
in_train <- createDataPartition(College$Expend, p = 3 / 4, list = FALSE)
training <- College[in_train, ]
testing <- College[-in_train, ]
```
b.
```{r, message=False}
train_model <- lm(Outstate ~ (.)^2 + I(Apps^2) + I(Accept^2) + I(Enroll^2) + I(Top10perc^2) + 
                   I(Top25perc^2) + I(F.Undergrad^2) + I(P.Undergrad^2) + I(Room.Board^2) + 
                   I(Books^2) + I(Personal^2) + I(PhD^2) + I(Terminal^2) + I(S.F.Ratio^2) + 
                   I(perc.alumni^2) + I(Expend^2) + I(Grad.Rate^2), data = training)

train_model_step <- step(train_model, trace = FALSE)
names(coef(train_model_step))
```
c.
```{r, message=False}
cv_var<- trainControl(method = "cv", number = 10)
gam <- data.frame(df = 1:10)
fit <- train(Outstate ~ Apps + Accept + Enroll + Top10perc +Top25perc + F.Undergrad + P.Undergrad + Room.Board +
Books + Personal + PhD + Terminal + S.F.Ratio +perc.alumni + Expend + Grad.Rate, data = training,method = "gamSpline", tuneControl = cv_var, tuneGrid = gam)
plot(fit$finalModel, residuals = TRUE, pch = ".", las = 1, rug = FALSE)
```
d.
Personal and maybe Expend
e.
```{r}
ase <- predict(fit, newdata = testing)
defaultSummary(data.frame(obs = testing$Outstate, pred = ase))
```

The average SSR is smaller in testing data for the gam model than the linearmodel.

##Problem 2: Lasso

```{r}
install.packages("flam")
```
a. Is the model in which each additive function is estimated to be piecewise constant with a small number of adaptively-chosen knots. 

b.
```{r}
library(flam)
X <- model.matrix(Outstate ~ . , data = training)
fit <- flamCV(x = X, y = training$Outstate)
yhat <- predict(fit$flam.out,new.x = model.matrix(Outstate ~ . , data = testing),lambda = fit$lambda.cv)
defaultSummary(data.frame(obs = testing$Outstate, pred = yhat))
```


##Problem 3

```{r, message=False}
payback <- readRDS("payback.rds")
payback
```

a.
```{r, message=False}

set.seed(915422914)

payback_split <- createDataPartition(payback$y, p = 0.5, list = FALSE)
training <- payback[ payback_split, ]
testing  <- payback[-payback_split, ]
```

b.
```{r, message=False}
logit <- glm(y ~ (.)^2 + I(loan_amnt^2) + I(int_rate^2) +I(installment^2) + I(emp_length^2) + I(annual_inc^2) + I(earliest_cr_line^2) +I(open_acc^2) + I(pub_rec^2) + I(revol_bal^2) + I(total_acc^2),data = training, family = binomial(link = "logit"))
```


